backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "welcome"
    label: "Welcome Section"
    files:
      - label: "Welcome Content"
        name: "welcome"
        file: "content/welcome.md"
        fields:
          - { label: "Title", name: "title", widget: "string" }
          - { label: "Description", name: "description", widget: "text" }

  - name: "footer"
    label: "Footer Section"
    files:
      - label: "Footer Text"
        name: "footer"
        file: "content/footer.md"
        fields:
          - { label: "Message", name: "message", widget: "string" }
